openapi: 3.0.0
info:
  title: Auth API
  version: 1.0.0
  description: API xác thực tài khoản người dùng

paths:
  /api/auth/register:
    post:
      summary: Đăng ký tài khoản
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: Đăng ký thành công
        '400':
          description: Dữ liệu không hợp lệ

  /api/auth/login:
    post:
      summary: Đăng nhập
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Đăng nhập thành công
        '400':
          description: Sai tài khoản hoặc mật khẩu

  /api/auth/logout:
    post:
      summary: Đăng xuất
      tags:
        - Auth
      responses:
        '200':
          description: Đăng xuất thành công

  /api/auth/otp/request:
    post:
      summary: Gửi yêu cầu OTP
      tags:
        - Auth
      responses:
        '200':
          description: OTP đã được gửi

  /api/auth/otp/verify:
    post:
      summary: Xác thực mã OTP
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                otpCode:
                  type: string
      responses:
        '200':
          description: Xác thực thành công

  /api/auth/forgot-password:
    post:
      summary: Yêu cầu đặt lại mật khẩu
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '200':
          description: Yêu cầu thành công

  /api/auth/reset-password:
    post:
      summary: Đặt lại mật khẩu
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                newPassword:
                  type: string
      responses:
        '200':
          description: Đặt lại mật khẩu thành công
