openapi: 3.0.3
info:
  title: Gateway API
  version: 1.0.0
  description: API Specification
servers:
  - url: 'http://localhost:3000'
  - url: 'http://localhost:3001'
  - url: 'http://localhost:3002'
paths:
  /api/auth/register:
    post:
      summary: Register New Account
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fname:
                  type: string
                mname:
                  type: string
                lname:
                  type: string
                password:
                  type: string
                email:
                  type: string
                avata:
                  type: string
      responses:
        '201':
          description: Register Successfully
        '400':
          description: Validation Error
        '500':
          description: Internal Server Error
  /api/auth/login:
    post:
      summary: Login
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login Successfully
        '400':
          description: Wrong Password or Email
  /api/auth/otp/request:
    post:
      summary: Request OTP through email
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                uid:
                  type: string
                email:
                  type: string
      responses:
        '200':
          description: OTP is sent successfully
        '400':
          description: Email missed
        '404':
          description: User not found
  /api/auth/otp/verify:
    post:
      summary: OTP Verification
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                otpCode:
                  type: string
                uid:
                  type: string
                email:
                  type: string
      responses:
        '200':
          description: Verify Successfully
        '400':
          description: Invalid OTP
        '404':
          description: User Not Found
  /api/course/get-all-course:
    get:
      summary: Get All Course
      tags:
        - Course
      parameters:
        - name: filter
          in: query
          required: false
          description: 'Compare [filter] with substring of [title, description]'
          schema:
            type: string
            default: ''
        - name: limit
          in: query
          required: false
          description: Maximum numbers of courses in each response
          schema:
            type: integer
            minimum: 0
            default: 4
        - name: offset
          in: query
          required: false
          description: Start index of course set
          minimum: 0
          default: 0
      responses:
        '200':
          description: Access Successfully
        '500':
          description: Internal Server Error
  '/api/course/get-course/{course_id}':
    get:
      summary: Get Course Details By ID
      tags:
        - Course
      parameters:
        - name: course_id
          in: path
          required: true
          description: The unique ID of a course
          schema:
            type: string
      responses:
        '200':
          description: Get course successfully
        '500':
          description: Get course failed
