openapi: 3.0.3
info:
  title: Gateway API
  version: 1.0.0
  description: API Specification

components:
  securitySchemes:
    bearerAuth:        # tên có thể đặt tùy ý
      type: http
      scheme: bearer
      bearerFormat: JWT   # để swagger UI biết đây là JWT

servers:
  - url: http://localhost:3000
  - url: http://localhost:3001
  - url: http://localhost:3002

paths:
  /api/auth/register:
    $ref: './auth.yaml#/paths/~1api~1auth~1register'
  /api/auth/login:
    $ref: './auth.yaml#/paths/~1api~1auth~1login'
  /api/auth/otp/request:
    $ref: './auth.yaml#/paths/~1api~1auth~1otp~1request'
  /api/auth/otp/verify:
    $ref: './auth.yaml#/paths/~1api~1auth~1otp~1verify'       
  /api/course/get-all-course:
    $ref: './course.yaml#/paths/~1api~1course~1get-all-course'
    security:
      - bearerAuth: []
  /api/course/get-course/{course_id}:
    $ref: './course.yaml#/paths/~1api~1course~1get-course~1{course_id}'
  /users:
    $ref: './user.yaml#/paths/~1users'

